services:
  stripe-api-service:
    working_dir: /usr/src/app
    build: .
    ports:
     - "3333:3333"
    networks:
    - stripe-api-network
    restart: always
networks:
  stripe-api-network:
    name: stripe-api-network